<?php

namespace Database\Seeders;

use App\Domains\Test\Models\Test;
use Illuminate\Database\Seeder;

class TestSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'name' => 'Launch checklist',
                'email' => 'ops@example.com',
                'description' => 'Pre-release QA checklist for the admin kit.',
                'status' => 'active',
                'category' => 'product',
                'priority' => 5,
                'score' => 92,
                'is_featured' => true,
                'is_public' => true,
                'tags' => ['alpha', 'urgent'],
                'metadata' => [
                    [
                        'title' => 'Launch notes',
                        'kind' => 'note',
                        'body' => 'Ship schema forms and DataTable polish.',
                        'image' => '/admin-logo.svg',
                        'enabled' => true,
                    ],
                    [
                        'title' => 'Cover asset',
                        'kind' => 'asset',
                        'body' => 'Optional hero image for this test.',
                        'image' => '',
                        'enabled' => true,
                    ],
                ],
                'published_at' => now()->subDays(2),
                'notes' => 'High priority showcase record.',
                'cover_image' => '/admin-logo.svg',
                'checklist' => ['Wire schema forms', 'Polish DataTable', 'Ship settings page'],
            ],
            [
                'name' => 'Draft pricing notes',
                'email' => 'billing@example.com',
                'description' => 'Ideas for pricing page copy.',
                'status' => 'draft',
                'category' => 'billing',
                'priority' => 2,
                'score' => 40,
                'is_featured' => false,
                'is_public' => false,
                'tags' => ['internal'],
                'metadata' => [
                    [
                        'title' => 'Pricing draft',
                        'kind' => 'note',
                        'body' => 'Keep private until legal review.',
                        'image' => '',
                        'enabled' => false,
                    ],
                ],
                'published_at' => null,
                'notes' => 'Keep private until legal review.',
            ],
            [
                'name' => 'Support escalation template',
                'email' => 'support@example.com',
                'description' => 'Template for VIP escalation threads.',
                'status' => 'active',
                'category' => 'support',
                'priority' => 4,
                'score' => 78,
                'is_featured' => true,
                'is_public' => true,
                'tags' => ['beta', 'urgent'],
                'metadata' => [
                    'source' => 'api',
                    'owner' => 'alex',
                    'flags' => ['reviewed' => true, 'synced' => false],
                    'sla_hours' => 4,
                ],
                'published_at' => now()->subWeek(),
                'notes' => null,
            ],
            [
                'name' => 'Archived onboarding flow',
                'email' => 'product@example.com',
                'description' => 'Old onboarding steps replaced in v2.',
                'status' => 'archived',
                'category' => 'product',
                'priority' => 1,
                'score' => 15,
                'is_featured' => false,
                'is_public' => false,
                'tags' => ['demo'],
                'metadata' => [
                    'source' => 'web',
                    'owner' => 'mina',
                    'flags' => ['reviewed' => true, 'synced' => true],
                    'version' => '1.4',
                ],
                'published_at' => now()->subMonths(3),
                'notes' => 'Retained for historical reference.',
            ],
            [
                'name' => 'General feedback inbox',
                'email' => 'hello@example.com',
                'description' => 'Catch-all feedback from early adopters.',
                'status' => 'active',
                'category' => 'general',
                'priority' => 3,
                'score' => 66,
                'is_featured' => false,
                'is_public' => true,
                'tags' => ['alpha', 'demo'],
                'metadata' => [
                    'source' => 'web',
                    'owner' => 'admin',
                    'flags' => ['reviewed' => false, 'synced' => true],
                    'channels' => ['email', 'chat'],
                ],
                'published_at' => now()->subDays(5),
                'notes' => 'Triage weekly.',
            ],
            [
                'name' => 'Invoice retry policy',
                'email' => 'finance@example.com',
                'description' => 'Rules for failed payment retries.',
                'status' => 'draft',
                'category' => 'billing',
                'priority' => 4,
                'score' => 55,
                'is_featured' => false,
                'is_public' => false,
                'tags' => ['internal', 'urgent'],
                'metadata' => [
                    'source' => 'api',
                    'owner' => 'lena',
                    'flags' => ['reviewed' => false, 'synced' => false],
                    'max_retries' => 3,
                ],
                'published_at' => null,
                'notes' => 'Needs finance sign-off.',
            ],
            [
                'name' => 'Demo tenant walkthrough',
                'email' => 'sales@example.com',
                'description' => 'Scripted demo for sales calls.',
                'status' => 'active',
                'category' => 'general',
                'priority' => 3,
                'score' => 88,
                'is_featured' => true,
                'is_public' => true,
                'tags' => ['demo', 'beta'],
                'metadata' => [
                    'source' => 'import',
                    'owner' => 'sales',
                    'flags' => ['reviewed' => true, 'synced' => true],
                    'duration_minutes' => 20,
                ],
                'published_at' => now()->subDays(1),
                'notes' => 'Include settings + schema tabs.',
            ],
            [
                'name' => 'Nightly sync report',
                'email' => 'devops@example.com',
                'description' => 'Summary of overnight sync jobs.',
                'status' => 'active',
                'category' => 'support',
                'priority' => 2,
                'score' => 71,
                'is_featured' => false,
                'is_public' => false,
                'tags' => ['internal'],
                'metadata' => [
                    'source' => 'api',
                    'owner' => 'ops',
                    'flags' => ['reviewed' => true, 'synced' => true],
                    'jobs' => ['users', 'tests', 'media'],
                ],
                'published_at' => now()->subHours(8),
                'notes' => null,
            ],
            [
                'name' => 'Legacy CSV importer',
                'email' => 'data@example.com',
                'description' => 'Importer used during migration week.',
                'status' => 'archived',
                'category' => 'product',
                'priority' => 1,
                'score' => 22,
                'is_featured' => false,
                'is_public' => false,
                'tags' => ['alpha'],
                'metadata' => [
                    'source' => 'import',
                    'owner' => 'data',
                    'flags' => ['reviewed' => true, 'synced' => false],
                    'rows_imported' => 12450,
                ],
                'published_at' => now()->subMonths(6),
                'notes' => 'Replaced by API ingest.',
            ],
            [
                'name' => 'Feature flag experiments',
                'email' => 'growth@example.com',
                'description' => 'A/B flags for growth experiments.',
                'status' => 'draft',
                'category' => 'product',
                'priority' => 5,
                'score' => 60,
                'is_featured' => true,
                'is_public' => true,
                'tags' => ['beta', 'demo', 'urgent'],
                'metadata' => [
                    'source' => 'web',
                    'owner' => 'growth',
                    'flags' => ['reviewed' => false, 'synced' => true],
                    'experiments' => [
                        ['key' => 'new_nav', 'pct' => 25],
                        ['key' => 'dense_table', 'pct' => 50],
                    ],
                ],
                'published_at' => null,
                'notes' => 'JSON metadata exercises the JsonInput field.',
            ],
        ];

        foreach ($records as $record) {
            Test::query()->updateOrCreate(
                ['name' => $record['name']],
                $record,
            );
        }
    }
}
